### ISSUE TITLE
It isn't possible add more headers to a request

### ISSUE THREAD

**Issue by martin-dominguez** [ethib137/liferay-react-native-demo#24]
https://github.com/ethib137/liferay-react-native-demo/blob/35cafffaff14deb378d3d78c69bd27eafc705fd9/src/util/configureRequest.js#L105-L116

Hey @ethib137, I'm opening this as a issue but it's more a thought  :) 

Sometimes I need to create new requests and add headers, for example "Accept-Language" that can be used to get/put localized data from 7.3. and I'd love to use the CreateRequest utility, but as can be checked in the lines included, if I include a "headers" object in the options the Authentication and Content-type headers that the utility configures by default are removed. What is the best approach to include headers? I changed those lines using this code.

```
		const auth = await getAuth();

		if (!auth) {
			throw new Error('Unable to make request. Please log in.');
		}

		let requestHeaders = {
			Authorization: `${auth.token_type} ${auth.access_token}`,
			'Content-Type': contentType,
		};

		request.headers = {
			...requestHeaders,
			...headers};
```

So far everything seems to work well, but it's just a suggestion.
Thanks!!

**Comment by ethib137** [comment]
Hey @martin-dominguez, this seems like a good change to make to the createRequest utility more robust. If you send me a pull I'll happily merge it in.

**Comment by ethib137** [comment]
Merged: https://github.com/ethib137/liferay-react-native-demo/commit/48095404394503e53b6f9fb3b060e8b28d53c9ea
