### ISSUE TITLE
Forms don't send data when default locale is not en_US

### ISSUE THREAD

**Issue by martin-dominguez** [ethib137/liferay-react-native-demo#25]
When you configure your portal instance using a locale different of en_US as default locale, when you try to submit a form the API return the following message:
` "title": "Invalid default locale set for field name Fieldxxxxxxxx",`

To make it work it's needed to include the "Accept-Language" header as this ticket is pointing out: https://issues.liferay.com/browse/LPS-123596

Please check #24 to see more about how to include new headers to a request.

This is the proposal to submit the data:
```
    request(
		`/o/headless-form/v1.0/forms/${formId}/form-records`,
		{
			data: {
				draft: false,
				formFieldValues: prepareValuesForSubmit(
					values,
					form.structure.formPages
				),
			},
			method: 'POST',
			headers: {
				'Accept-Language': `${state.lang.replace("_","-")}`,
			},
		}
	).then(() => {
		resetForm();
		setSubmitting(false);
		setLoading(false);
    });
```

Bear in mind that #24  is required to make it work.

Thanks!

**Comment by ethib137** [comment]
Hey @martin-dominguez this also seems like a good idea. You're welcome to include both tickets in a single pull, especially since that will make it easier to test.

**Comment by ethib137** [comment]
Merged: https://github.com/ethib137/liferay-react-native-demo/commit/48095404394503e53b6f9fb3b060e8b28d53c9ea
